name: hti_univerity
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #    An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 file
  flutter_svg: ^2.0.17
  # Metadata A powerful HTTP networking package, supports Interceptors,  Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio:
  #  A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
  retrofit:
  #  retrofit.dart is an dio client generator using source_gen and inspired by Chopper and Retrofit.
  logger:
  #    Small, easy to use and extensible logger which prints beautiful log
  json_annotation: ^4.9.0

  #  Classes and helper functions that support JSON code generation via the `json_serializable` package
  bloc:
  #  Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc:
  #  Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it:
  #  injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart
  injectable:
  #    Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android
  flutter_secure_storage:
  #    A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil:
  #    flutter_localizations
  #  Flutter Localization is a package use for in-app localization with map data. More easier and faster to implement and inspired by the flutter_localizations itself
  flutter_localizations:
    sdk: flutter
  intl: any
  #  Flutter package to show beautiful dialogs(INFO,QUESTION,WARNING,SUCCESS,ERROR) with animations as simply as possible
  awesome_dialog:
  #    Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player
  lottie:
  #  Flutter library to load and cache network images. Can also be used with placeholder and error widgets
  cached_network_image:
  #    A flutter package which will help you to generate pin code fields. Can be useful for OTP for example.
  pin_code_fields:
  #Library that allows you to display progress widgets based on percentage, can be Circular or Linear, you can also customize it to your needs.
  percent_indicator:
  #    Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256
  hive:
  #    Extension for Hive. Makes it easier to use Hive in Flutter apps
  hive_flutter:
  #    A powerful and easy-to-use SQLite database for Flutter apps. It supports both iOS and Android platforms.
  smooth_page_indicator: ^1.2.0+3
    #    A Flutter package for creating a smooth and customizable page indicator
  auto_size_text:
    #    A Flutter widget that automatically resizes text to fit perfectly within its bounds
  provider: ^6.1.4
    #    A Flutter package for creating a smooth and customizable page indicator
  image_picker: ^1.1.2
    #    A Flutter package for creating a smooth and customizable page indicator
  file_picker:
dev_dependencies:

  injectable_generator:
  build_runner:
  retrofit_generator:
  hive_generator:
  json_serializable:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/animations/
    - assets/images/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter_Bold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset:  assets/fonts/inter/Inter_Light.ttf
          weight: 300
